### Get Dziady
GET localhost:8081/book/3


### Get all
GET localhost:8081/book



### Get books for author with id = 3
GET localhost:8081/book/author/3



### Create Treny
POST localhost:8081/book
Content-Type: application/json

{
  "title": "Treny",
  "pages": 300,
  "authorIds": []
}


### Update Potop
PUT localhost:9000/book/1
Content-Type: application/json

{
  "title": "Potop 2",
  "pages": 2137,
  "authorIds": [2, 3]
}


### Delete Treny
DELETE localhost:8081/book/4
